# Generated by Django 4.2.28 on 2026-05-07 02:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landcover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('phcode_reg', models.CharField(blank=True, max_length=254, null=True)),
                ('reg_name', models.CharField(blank=True, max_length=254, null=True)),
                ('phcode_pro', models.CharField(blank=True, max_length=254, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=254, null=True)),
                ('phcode_mun', models.CharField(blank=True, max_length=254, null=True)),
                ('mun_name', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'gis"."ph_muni',
                'managed': False,
            },
        ),
    ]
