# Generated by Django 4.2.30 on 2026-05-07 03:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landcover', '0002_municipality'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandCover',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('classname', models.CharField(blank=True, db_column='descript', max_length=120, null=True)),
                ('province', models.CharField(blank=True, max_length=80, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(db_column='geom', srid=4326)),
            ],
            options={
                'db_table': 'landcover_polygon',
                'managed': False,
            },
        ),
    ]
