# Generated by Django 4.2.30 on 2026-05-07 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landcover', '0003_landcover_delete_landcoverpolygon'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='municipality',
            table='ph_muni',
        ),
    ]
