# Generated by Django 4.2.30 on 2026-05-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landcover', '0004_alter_municipality_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='landcover',
            table='landcover_polygons',
        ),
    ]
